apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraping-service
  template:
    metadata:
      labels:
        app: scraping-service
    spec:
      containers:
      - name: scraper
        image: devopsrakeshrestha/crawl:POC-01
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: access-key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: secret-key
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws-region
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: bucket_name
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "1000Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 6
        startupProbe:                    
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15       
          periodSeconds: 10             
          failureThreshold: 30
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-crawler
            topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        yourNodeLabelKey: scraping-server
      imagePullSecrets:
        - name: acr-auth
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
