apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: poc
data:
  access-key: eW91ciBrZXlz
  secret-key: eW91ciBrZXlz
  aws-region: eW91ciBrZXlz
  bucket-name: eW91ciBrZXlz
type: Opaque
